server {
    listen 80;
    server_name localhost;

    # Document root
    root /home/ama55id/rnaanalyzer/htdocs;
    index server.html;

    # CGI handling
    location /cgi-bin/ {
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /home/ama55id/rnaanalyzer$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_connect_timeout 300s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;

        # Optional: Set DOCUMENT_ROOT to the directory where your CGI scripts are located
        fastcgi_param DOCUMENT_ROOT /home/ama55id/rnaanalyzer;
    }

    # Static files handling (HTML, CSS, JS, etc.)
    location / {
        try_files $uri $uri/ =404;
        autoindex on;
        allow all;
    }

    # Handling the tmp directory
    location /tmp/ {
        alias /home/ama55id/rnaanalyzer/tmp/;
        autoindex on;
        allow all;
    }


}
