server {
    listen 80;
    server_name localhost;

    # Document root
    root /mnt/c/Users/ama55id/Nextcloud/RNA_analyzer/rnaanalyzer/htdocs;
    index index.html;

    # CGI handling
    location /cgi-bin/ {
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /mnt/c/Users/ama55id/Nextcloud/RNA_analyzer/rnaanalyzer$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;

        # Optional: Set DOCUMENT_ROOT to the directory where your CGI scripts are located
        fastcgi_param DOCUMENT_ROOT /mnt/c/Users/ama55id/Nextcloud/RNA_analyzer/rnaanalyzer;
    }

    # Static files handling (HTML, CSS, JS, etc.)
    location / {
        try_files $uri $uri/ =404;
        autoindex on;
        allow all;
    }
    
    # Handling the tmp directory
    location /tmp/ {
        alias /mnt/c/Users/ama55id/Nextcloud/RNA_analyzer/rnaanalyzer/tmp/;
        autoindex on;
        allow all;
    }


}

